In [ ]:
# Imports
from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive
from google.colab import auth
from oauth2client.client import GoogleCredentials
import pandas as pd
import numpy as np

In [ ]:
# Do not run again once obtained zip file
# Login to GoogeDrive to retrieve uploaded .zip file
auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

In [ ]:
downloaded0 = drive.CreateFile({'id': '1W45veu7NEtmcqmuJjXmM_SfvEvXrTKgM'})
downloaded0.GetContentFile('1_2018_3_2018.csv')
downloaded1 = drive.CreateFile({'id': '1S1t6WNuHO6BkCFROko2QawIaJnwpGBWT'})
downloaded1.GetContentFile('4_2018_6_2018.csv')
downloaded2 = drive.CreateFile({'id': '1wmr7tbXqQAMhEZLvmm67inu7FalvPMPX'})
downloaded2.GetContentFile('7_2018_9_2018.csv')
downloaded3 = drive.CreateFile({'id': '17ZyxEAYLeO7G1urypi5c_p0oHfdYA7Qv'})
downloaded3.GetContentFile('10_2018_12_2018.csv')

In [ ]:
df1 = pd.read_csv('1_2018_3_2018.csv')
df2 = pd.read_csv('4_2018_6_2018.csv')
df3 = pd.read_csv('7_2018_9_2018.csv')
df4 = pd.read_csv('10_2018_12_2018.csv')

In [ ]:
all_18 = [df1, df2, df3, df4]
df_18 = pd.concat(all_18)

In [ ]:
df_18

       Stn Id    Stn Name        CIMIS Region  ... qc.12  Avg Soil Temp (F)  qc.13
0           2  FivePoints  San Joaquin Valley  ...                     51.1
1           2  FivePoints  San Joaquin Valley  ...                     51.3
2           2  FivePoints  San Joaquin Valley  ...                     51.3
3           2  FivePoints  San Joaquin Valley  ...                     53.0
4           2  FivePoints  San Joaquin Valley  ...                     54.4
...       ...         ...                 ...  ...   ...                ...    ...
13740     258  Lemon Cove  San Joaquin Valley  ...     M               55.3
13741     258  Lemon Cove  San Joaquin Valley  ...     M               53.9
13742     258  Lemon Cove  San Joaquin Valley  ...     M               52.7
13743     258  Lemon Cove  San Joaquin Valley  ...                     51.9
13744     258  Lemon Cove  San Joaquin Valley  ...     M               51.4      P

[53637 rows x 33 columns]

In [ ]:
downloaded00 = drive.CreateFile({'id': '12qpKaO3_9ObFUgB0LAaVUBVgrEwETurY'})
downloaded00.GetContentFile('1_2019_3_2019.csv')
downloaded11 = drive.CreateFile({'id': '1fFXiA52uyzNqyvlnDVmr1Tx5ZIXDl2f6'})
downloaded11.GetContentFile('4_2019_6_2019.csv')
downloaded22 = drive.CreateFile({'id': '1d-QUU8zc2CirTbYf5uiXAE-iTtIIngMg'})
downloaded22.GetContentFile('7_2019_9_2019.csv')
downloaded33 = drive.CreateFile({'id': '13s_LyW8plqBISXq1HTS26F7mFGBBzBas'})
downloaded33.GetContentFile('10_2019_12_2019.csv')

In [ ]:
df11 = pd.read_csv('1_2019_3_2019.csv')
df22 = pd.read_csv('4_2019_6_2019.csv')
df33 = pd.read_csv('7_2019_9_2019.csv')
df44 = pd.read_csv('10_2019_12_2019.csv')

In [ ]:
all_19 = [df11, df22, df33, df44]
df_19 = pd.concat(all_19)

In [ ]:
df_19

       Stn Id    Stn Name        CIMIS Region  ... qc.12  Avg Soil Temp (F)  qc.13
0           2  FivePoints  San Joaquin Valley  ...                     48.8
1           2  FivePoints  San Joaquin Valley  ...                     47.9
2           2  FivePoints  San Joaquin Valley  ...                     47.7
3           2  FivePoints  San Joaquin Valley  ...                     47.7
4           2  FivePoints  San Joaquin Valley  ...                     48.3
...       ...         ...                 ...  ...   ...                ...    ...
14071     261     Gazelle   Northeast Plateau  ...                     34.3
14072     261     Gazelle   Northeast Plateau  ...                     33.9
14073     261     Gazelle   Northeast Plateau  ...                     34.9
14074     261     Gazelle   Northeast Plateau  ...                     36.5
14075     261     Gazelle   Northeast Plateau  ...                     36.3

[55107 rows x 33 columns]

In [ ]:
downloaded000 = drive.CreateFile({'id': '1Wkq1-2SLML4EgnC_phMqqsKRzmv52ubO'})
downloaded000.GetContentFile('1_2020_3_2020.csv')
downloaded111 = drive.CreateFile({'id': '10Ikt-QDEVX2Cg463kG8UZJ62-1dlyRS8'})
downloaded111.GetContentFile('4_2020_6_2020.csv')
downloaded222 = drive.CreateFile({'id': '1Ezs6CIoTL4IZ0UDKuaVEiZtpf3h9Hc5t'})
downloaded222.GetContentFile('7_2020_9_2020.csv')

In [ ]:
df111 = pd.read_csv('1_2020_3_2020.csv')
df222 = pd.read_csv('4_2020_6_2020.csv')
df333 = pd.read_csv('7_2020_9_2020.csv')

In [ ]:
all_20 = [df111, df222, df333]
df_20 = pd.concat(all_20)

In [ ]:
df_20

       Stn Id    Stn Name        CIMIS Region  ... qc.12  Avg Soil Temp (F)  qc.13
0           2  FivePoints  San Joaquin Valley  ...                     50.8
1           2  FivePoints  San Joaquin Valley  ...                     52.0
2           2  FivePoints  San Joaquin Valley  ...                     51.5
3           2  FivePoints  San Joaquin Valley  ...                     51.6
4           2  FivePoints  San Joaquin Valley  ...                     51.8
...       ...         ...                 ...  ...   ...                ...    ...
11545     262      Linden  San Joaquin Valley  ...                     70.6
11546     262      Linden  San Joaquin Valley  ...                     69.7
11547     262      Linden  San Joaquin Valley  ...                     69.4
11548     262      Linden  San Joaquin Valley  ...                     69.2
11549     262      Linden  San Joaquin Valley  ...                     70.3

[39522 rows x 33 columns]

In [ ]:
df_20.columns

Index(['Stn Id', 'Stn Name', 'CIMIS Region', 'Date', 'Jul', 'ETo (in)', 'qc',
       'Precip (in)', 'qc.1', 'Sol Rad (Ly/day)', 'qc.2',
       'Avg Vap Pres (mBars)', 'qc.3', 'Max Air Temp (F)', 'qc.4',
       'Min Air Temp (F)', 'qc.5', 'Avg Air Temp (F)', 'qc.6',
       'Max Rel Hum (%)', 'qc.7', 'Min Rel Hum (%)', 'qc.8', 'Avg Rel Hum (%)',
       'qc.9', 'Dew Point (F)', 'qc.10', 'Avg Wind Speed (mph)', 'qc.11',
       'Wind Run (miles)', 'qc.12', 'Avg Soil Temp (F)', 'qc.13'],
      dtype='object')

In [ ]:
fires18 = drive.CreateFile({'id': '1MUFRzAX-RmO_tiyjae2cw7yZ4w-ioauL'})
fires18.GetContentFile('2018_fires.csv')

In [ ]:
fires18 = pd.read_csv('2018_fires.csv')
notes18 = fires18.pop('Notes')
fires18['Start date'] = pd.to_datetime(fires18['Start date'], format='%B %d, %Y')
fires18['Start date'] = fires18['Start date'].apply(lambda x: x.strftime('%-m/%-d/%Y'))
fires18['Containment date'] = pd.to_datetime(fires18['Containment date'], format='%B %d, %Y')
fires18['Containment date'] = fires18['Containment date'].apply(lambda x: x.strftime('%-m/%-d/%Y'))

In [ ]:
fires18[['Start date','Containment date']] = fires18[['Start date','Containment date']].apply(pd.to_datetime)
fires2018 = fires18.loc[fires18.index.repeat((fires18['Containment date'] - fires18['Start date']).dt.days + 1)]
fires2018['Date'] = fires2018['Start date'] + pd.to_timedelta(fires2018.groupby(level=0).cumcount(), unit='d')
fires2018 = fires2018.reset_index(drop=True)
fires2018.drop(['Start date', 'Containment date'], axis=1, inplace=True)
fires2018['Date'] = pd.to_datetime(fires2018['Date'], format='%B %d, %Y')
fires2018['Date'] = fires2018['Date'].apply(lambda x: x.strftime('%-m/%-d/%Y'))

In [ ]:
fires2018

       Stn Name                County        Date
0        Bishop                  Inyo   2/18/2018
1        Bishop                  Inyo   2/19/2018
2        Bishop                  Inyo   2/20/2018
3        Bishop                  Inyo   2/21/2018
4        Bishop                  Inyo   2/22/2018
...         ...                   ...         ...
1220  Camarillo  Los Angeles, Ventura  11/18/2018
1221  Camarillo  Los Angeles, Ventura  11/19/2018
1222  Camarillo  Los Angeles, Ventura  11/20/2018
1223  Camarillo  Los Angeles, Ventura  11/21/2018
1224  Camarillo  Los Angeles, Ventura  11/22/2018

[1225 rows x 3 columns]

In [ ]:
stations_ = drive.CreateFile({'id': '1q8MCC8ebs29LmGj6-K-S8_PXgsvLPSlc'})
stations_.GetContentFile('cimis_station_list.csv')

In [ ]:
stations = pd.read_csv('cimis_station_list.csv')
stations = stations.rename(columns={'Fresno/F.S.U. USDA': 'Stn Name', 'Fresno': 'County', 'Inactive': 'Status'})
stations.drop('1', axis=1, inplace=True)
stations = stations[stations['Status'] == 'Active']

In [ ]:
stations

             Stn Name       County  Status
0          FivePoints       Fresno  Active
3             Shafter         Kern  Active
4               Davis         Yolo  Active
5    Firebaugh/Telles       Fresno  Active
10             Durham        Butte  Active
..                ...          ...     ...
256        Lemon Cove       Tulare  Active
257    Ferndale Plain     Humboldt  Active
258          Montague     Siskiyou  Active
259           Gazelle     Siskiyou  Active
260            Linden  San Joaquin  Active

[154 rows x 3 columns]

In [ ]:
fires19 = drive.CreateFile({'id': '1IBDg9Ro-3Bk8XpYVdC6JLlofYjMjHb0f'})
fires19.GetContentFile('2019_fires.csv')

In [ ]:
fires19 = pd.read_csv('2019_fires.csv')
notes19 = fires19.pop('Notes')
fires19['Start date'] = pd.to_datetime(fires19['Start date'], format='%B %d')
fires19['Start date'] = fires19['Start date'].apply(lambda x: x.strftime('%-m/%-d/2019'))
fires19['Containment date'] = pd.to_datetime(fires19['Containment date'], format='%B %d')
fires19['Containment date'] = fires19['Containment date'].apply(lambda x: x.strftime('%-m/%-d/2019'))

In [ ]:
fires19[['Start date','Containment date']] = fires19[['Start date','Containment date']].apply(pd.to_datetime)
fires2019 = fires19.loc[fires19.index.repeat((fires19['Containment date'] - fires19['Start date']).dt.days + 1)]
fires2019['Date'] = fires2019['Start date'] + pd.to_timedelta(fires2019.groupby(level=0).cumcount(), unit='d')
fires2019 = fires2019.reset_index(drop=True)
fires2019.drop(['Start date', 'Containment date'], axis=1, inplace=True)
fires2019['Date'] = pd.to_datetime(fires2019['Date'], format='%B %d, %Y')
fires2019['Date'] = fires2019['Date'].apply(lambda x: x.strftime('%-m/%-d/%Y'))

In [ ]:
fires20 = drive.CreateFile({'id': '1OPJxlzRFpqKLomdWs2nmL8MIJrZA2eZs'})
fires20.GetContentFile('2020_fires.csv')
fires20 = pd.read_csv('2020_fires.csv')

In [ ]:
notes20 = fires20.pop('Notes')
fires20['Start date'] += ', 2020'
fires20['Containment date'] += ', 2020'

In [ ]:
fires20['Start date'] = pd.to_datetime(fires20['Start date'], format='%B %d, %Y')
fires20['Start date'] = fires20['Start date'].apply(lambda x: x.strftime('%-m/%-d/%Y'))
fires20['Containment date'] = pd.to_datetime(fires20['Containment date'], format='%B %d, %Y', errors='ignore')
fires20['Containment date'] = fires20['Containment date'].apply(lambda x: x.strftime('%-m/%-d/%Y'))

In [ ]:
fires20 = fires20.merge(stations, how='left', on=['County'])

In [ ]:
fires20['Stn Name'] = fires20['Stn Name_y']
fires20.drop(['Stn Name_x', 'County', 'Acres', 'Status', 'Stn Name_y'], axis=1, inplace=True)

In [ ]:
fires20 = fires20.dropna()

In [ ]:
fires20[['Start date','Containment date']] = fires20[['Start date','Containment date']].apply(pd.to_datetime)
fires2020 = fires20.loc[fires20.index.repeat((fires20['Containment date'] - fires20['Start date']).dt.days + 1)]
fires2020['Date'] = fires2020['Start date'] + pd.to_timedelta(fires2020.groupby(level=0).cumcount(), unit='d')
fires2020 = fires2020.reset_index(drop=True)
fires2020.drop(['Start date', 'Containment date'], axis=1, inplace=True)
fires2020['Date'] = pd.to_datetime(fires2020['Date'], format='%B %d, %Y')
fires2020['Date'] = fires2020['Date'].apply(lambda x: x.strftime('%-m/%-d/%Y'))

In [ ]:
#fires20.drop(['County', 'Acres'], axis=1, inplace=True)

In [ ]:
stations

             Stn Name       County  Status
0          FivePoints       Fresno  Active
3             Shafter         Kern  Active
4               Davis         Yolo  Active
5    Firebaugh/Telles       Fresno  Active
10             Durham        Butte  Active
..                ...          ...     ...
256        Lemon Cove       Tulare  Active
257    Ferndale Plain     Humboldt  Active
258          Montague     Siskiyou  Active
259           Gazelle     Siskiyou  Active
260            Linden  San Joaquin  Active

[154 rows x 3 columns]

In [ ]:
# df_18, df_19, df_20, fires2018, fires2019, fires2020

In [ ]:
df_18['Target'] = 0
fires2018['Target'] = 1

In [ ]:
df18 = df_18.merge(fires2018, how='left', on=['Stn Name','Date'])
df18['Target'] = np.where(df18['Target_y']==1.0, 1, 0)
df18.drop(['Target_x', 'County', 'Target_y'], axis=1, inplace=True)

In [ ]:
df18

       Stn Id    Stn Name        CIMIS Region  ... Avg Soil Temp (F)  qc.13  Target
0           2  FivePoints  San Joaquin Valley  ...              51.1              0
1           2  FivePoints  San Joaquin Valley  ...              51.3              0
2           2  FivePoints  San Joaquin Valley  ...              51.3              0
3           2  FivePoints  San Joaquin Valley  ...              53.0              0
4           2  FivePoints  San Joaquin Valley  ...              54.4              0
...       ...         ...                 ...  ...               ...    ...     ...
53812     258  Lemon Cove  San Joaquin Valley  ...              55.3              0
53813     258  Lemon Cove  San Joaquin Valley  ...              53.9              0
53814     258  Lemon Cove  San Joaquin Valley  ...              52.7              0
53815     258  Lemon Cove  San Joaquin Valley  ...              51.9              0
53816     258  Lemon Cove  San Joaquin Valley  ...              51.4      P       0

[53817 rows x 34 columns]

In [ ]:
df_19['Target'] = 0
fires2019['Target'] = 1

In [ ]:
df19 = df_19.merge(fires2018, how='left', on=['Stn Name','Date'])
df19['Target'] = np.where(df19['Target_y']==1.0, 1, 0)
df19.drop(['Target_x', 'County', 'Target_y'], axis=1, inplace=True)

In [ ]:
df19

       Stn Id    Stn Name        CIMIS Region  ... Avg Soil Temp (F)  qc.13  Target
0           2  FivePoints  San Joaquin Valley  ...              48.8              0
1           2  FivePoints  San Joaquin Valley  ...              47.9              0
2           2  FivePoints  San Joaquin Valley  ...              47.7              0
3           2  FivePoints  San Joaquin Valley  ...              47.7              0
4           2  FivePoints  San Joaquin Valley  ...              48.3              0
...       ...         ...                 ...  ...               ...    ...     ...
55102     261     Gazelle   Northeast Plateau  ...              34.3              0
55103     261     Gazelle   Northeast Plateau  ...              33.9              0
55104     261     Gazelle   Northeast Plateau  ...              34.9              0
55105     261     Gazelle   Northeast Plateau  ...              36.5              0
55106     261     Gazelle   Northeast Plateau  ...              36.3              0

[55107 rows x 34 columns]

In [ ]:
fires2020['Target'] = 1
df_20['Target'] = 0
df20 = df_20.merge(fires2020, how='left', on=['Stn Name','Date'])
df20['Target'] = np.where(df20['Target_y']==1.0, 1, 0)
df20.drop(['Target_x', 'Target_y'], axis=1, inplace=True)

In [ ]:
df_20

       Stn Id    Stn Name        CIMIS Region  ... Avg Soil Temp (F)  qc.13  Target
0           2  FivePoints  San Joaquin Valley  ...              50.8              0
1           2  FivePoints  San Joaquin Valley  ...              52.0              0
2           2  FivePoints  San Joaquin Valley  ...              51.5              0
3           2  FivePoints  San Joaquin Valley  ...              51.6              0
4           2  FivePoints  San Joaquin Valley  ...              51.8              0
...       ...         ...                 ...  ...               ...    ...     ...
11545     262      Linden  San Joaquin Valley  ...              70.6              0
11546     262      Linden  San Joaquin Valley  ...              69.7              0
11547     262      Linden  San Joaquin Valley  ...              69.4              0
11548     262      Linden  San Joaquin Valley  ...              69.2              0
11549     262      Linden  San Joaquin Valley  ...              70.3              0

[39522 rows x 34 columns]

In [ ]:
df20

       Stn Id    Stn Name        CIMIS Region  ... Avg Soil Temp (F)  qc.13  Target
0           2  FivePoints  San Joaquin Valley  ...              50.8              0
1           2  FivePoints  San Joaquin Valley  ...              52.0              0
2           2  FivePoints  San Joaquin Valley  ...              51.5              0
3           2  FivePoints  San Joaquin Valley  ...              51.6              0
4           2  FivePoints  San Joaquin Valley  ...              51.8              0
...       ...         ...                 ...  ...               ...    ...     ...
40736     262      Linden  San Joaquin Valley  ...              70.6              1
40737     262      Linden  San Joaquin Valley  ...              69.7              1
40738     262      Linden  San Joaquin Valley  ...              69.4              1
40739     262      Linden  San Joaquin Valley  ...              69.2              1
40740     262      Linden  San Joaquin Valley  ...              70.3              1

[40741 rows x 34 columns]

In [ ]:
# df18, df19, df20
to_concat = [df18, df19, df20]
df = pd.concat(to_concat, ignore_index=True)

In [ ]:
df

        Stn Id    Stn Name        CIMIS Region  ... Avg Soil Temp (F)  qc.13  Target
0            2  FivePoints  San Joaquin Valley  ...              51.1              0
1            2  FivePoints  San Joaquin Valley  ...              51.3              0
2            2  FivePoints  San Joaquin Valley  ...              51.3              0
3            2  FivePoints  San Joaquin Valley  ...              53.0              0
4            2  FivePoints  San Joaquin Valley  ...              54.4              0
...        ...         ...                 ...  ...               ...    ...     ...
149660     262      Linden  San Joaquin Valley  ...              70.6              1
149661     262      Linden  San Joaquin Valley  ...              69.7              1
149662     262      Linden  San Joaquin Valley  ...              69.4              1
149663     262      Linden  San Joaquin Valley  ...              69.2              1
149664     262      Linden  San Joaquin Valley  ...              70.3              1

[149665 rows x 34 columns]

In [ ]:
df = df.loc[:, ~df.columns.str.contains('^Unnamed')]

In [ ]:
col = ['Jul', 'qc', 'qc.1', 'qc.2', 'qc.3', 'qc.4', 'qc.5', 'qc.6', 'qc.7', 'qc.8', 'qc.9', 'qc.10', 'qc.11', 'qc.12', 'qc.13']
df.drop(col, axis=1, inplace=True)

In [ ]:
df = df.dropna()

In [ ]:
df.to_csv('conditions_df.csv')